# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celery_tasks.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celery_tasks.UserDetail'),
        ),
    ]
