# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0002_auto_20180422_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='user_id',
            new_name='user',
        ),
    ]
