# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celery_tasks', '0004_auto_20180422_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='celery_tasks.User'),
        ),
    ]
